/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package length;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class DatosPersonales_GV extends javax.swing.JFrame {

    /**
     * Creates new form DatosPersonales_GV
     */
    
    FondoPanel fondo = new FondoPanel();

    class FondoPanel extends JPanel{
    
    private Image imagen;
    
    @Override
    public void paint(Graphics g){
        
        imagen = new ImageIcon(getClass().getResource("/length/Imagenes/fondo.png")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(), (ImageObserver) this);
        setOpaque(false);
        super.paint(g);
        
    }

        private void setOPaque(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    
}
    
    
    
    public DatosPersonales_GV() {
        
        //this.setContentPane(fondo);
        this.setContentPane(fondo);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtTelfCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblTelfCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        lblImgUsuario = new javax.swing.JLabel();
        lblImgPassword = new javax.swing.JLabel();
        lblImgTelf = new javax.swing.JLabel();
        lblImgEmail = new javax.swing.JLabel();
        btnVista = new javax.swing.JButton();
        lblMn = new javax.swing.JLabel();
        lblMc = new javax.swing.JLabel();
        lblMp = new javax.swing.JLabel();
        lblMt = new javax.swing.JLabel();
        lblMe = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Nombre Completo: ");

        lblCedula.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(204, 204, 204));
        lblCedula.setText("Cedula:");

        lblPassword.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(204, 204, 204));
        lblPassword.setText("Contraseña: ");

        lblTelfCelular.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblTelfCelular.setForeground(new java.awt.Color(204, 204, 204));
        lblTelfCelular.setText("Telefono Celular: ");

        lblEmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(204, 204, 204));
        lblEmail.setText("Correo Electronico: ");

        lblTitulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("¡Bienvenido!");

        lblInstrucciones.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        lblInstrucciones.setText("Ingresar tus datos personales en las casillas");

        lblImgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/length/Imagenes/usuario.png"))); // NOI18N

        lblImgPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/length/Imagenes/contraseña.png"))); // NOI18N

        lblImgTelf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/length/Imagenes/celular.png"))); // NOI18N

        lblImgEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/length/Imagenes/email.png"))); // NOI18N

        btnVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/length/Imagenes/vista.jpg"))); // NOI18N
        btnVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaActionPerformed(evt);
            }
        });

        lblMn.setText("     ");

        lblMc.setText("     ");

        lblMp.setText("     ");

        lblMt.setText("     ");

        lblMe.setText("     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblInstrucciones)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnRegistrar)
                                .addGap(72, 72, 72))
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImgPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblImgUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblImgTelf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblImgEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCedula)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPassword)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelfCelular)
                                    .addComponent(txtTelfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMp)
                        .addGap(1, 1, 1)
                        .addComponent(btnVista))
                    .addComponent(lblMn)
                    .addComponent(lblMc)
                    .addComponent(lblMt)
                    .addComponent(lblMe))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInstrucciones)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMn))
                        .addGap(12, 12, 12)
                        .addComponent(lblCedula))
                    .addComponent(lblImgUsuario))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMp))
                            .addComponent(btnVista, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelfCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMt)))
                            .addComponent(lblImgTelf)))
                    .addComponent(lblImgPassword))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMe)))
                    .addComponent(lblImgEmail))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:

        String nombre = txtNombre.getText();
        String cedula = txtCedula.getText();
        String telf = txtTelfCelular.getText();
        String email = txtEmail.getText();
        String password = txtPassword.getText();
        
        
        
        this.expresionRegurarNombre(nombre);
        this.expresionRegurarCedula(cedula);
        this.expresionRegurarPassword(password);
        this.expresionRegurarTelf(telf);
        this.expresionRegurarEmail(email);
     
        if(!" ".equals(nombre)&& !" ".equals(cedula)&&!" ".equals(telf)
                && !" ".equals(email)&&!" ".equals(password)){
            lblMensaje.setForeground(Color.RED);
            lblMensaje.setText("Error, llenar todas los campos en blanco faltantes");
        }else{
            lblMensaje.setForeground(Color.GREEN);
          lblMensaje.setText("Su información fue registrada con exito");  
        }
                
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public void encriptarPassword (String password){
        String code = "";
        
        int longitud = password.length();
        
        for (int i = 0; i <= longitud; i++) {
            code += "*";
            
        }
        txtPassword.setText(code);
    }
    
    public void expresionRegurarNombre (String nombre){
        String validarNombre = "^[A-Za-zÁ-ÿ\\s'-]+$";    
        
        if (nombre.matches(validarNombre)) {
            lblMn.setForeground(Color.GREEN);
            lblMn.setText("✔");
        } else {
            lblMn.setForeground(Color.RED);
            lblMn.setText("✘");
        }
    }
    public void expresionRegurarCedula (String cedula){
        String validarCedula = "^[0-9]{10}$";
    
        if (cedula.matches(validarCedula)) {
            lblMc.setForeground(Color.GREEN);
            lblMc.setText("✔");
        } else {
            lblMc.setForeground(Color.RED);
            lblMc.setText("✘");
        }
    }
    
    public void expresionRegurarTelf (String telf){
        String validarEmail = "^09[0-9]{8}$";
    
        if (telf.matches(validarEmail)) {
            lblMt.setForeground(Color.GREEN);
            lblMt.setText("✔");
        } else {
            lblMt.setForeground(Color.RED);
            lblMt.setText("✘");
        }
    }
    
    public void expresionRegurarEmail (String email){
        String validarEmail = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    
        if (email.matches(validarEmail)) {
            lblMe.setForeground(Color.GREEN);
            lblMe.setText("✔");
        } else {
            lblMe.setForeground(Color.RED);
            lblMe.setText("✘");
        }
    }
    
    public void expresionRegurarPassword (String password){
        String validarPassword = "^(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{5,}$";
    
        if (password.matches(validarPassword)) {
            lblMp.setForeground(Color.GREEN);
            lblMp.setText("✔");
        } else {
            lblMp.setForeground(Color.RED);
            lblMp.setText("✘");
        }
    }

    private void btnVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaActionPerformed
        // TODO add your handling code here:
        String Password = txtPassword.getText();
                
        txtPassword.setText(Password);
    }//GEN-LAST:event_btnVistaActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        String password = txtPassword.getText();
        this.encriptarPassword(password);
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPersonales_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPersonales_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPersonales_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPersonales_GV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPersonales_GV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVista;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImgEmail;
    private javax.swing.JLabel lblImgPassword;
    private javax.swing.JLabel lblImgTelf;
    private javax.swing.JLabel lblImgUsuario;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblMc;
    private javax.swing.JLabel lblMe;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMn;
    private javax.swing.JLabel lblMp;
    private javax.swing.JLabel lblMt;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTelfCelular;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelfCelular;
    // End of variables declaration//GEN-END:variables







}

