
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author floow
 */
public class CadenasClase extends javax.swing.JFrame {

    /**
     * Creates new form CadenasClase
     */
    public CadenasClase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtTexto = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Cadenas vistas en clase");

        txtTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTextoActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnValidar)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTextoActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        this.EspaciosCadena1();
       this.NumeroVocales();
        String Texto = txtTexto.getText();

    // Separar la cadena cuando se encuentra un espacio en blanco y contar palabras
    int numPalabras = contarPalabras(Texto);

    // Reemplazar 'o' por '$' y 'a' por '@'
    String textoReemplazado = reemplazarCaracteres(Texto);

    // Obtener la oración al revés
    String textoAlReves = obtenerAlReves(Texto);

    // Mostrar resultados en la caja de texto de salida
    String resultado = "Palabras en la oración: " + numPalabras + "\n"
            + "Oracion remplazando 'o' por '$' y 'a' por '@': \n" + textoReemplazado + "\n"
            + "Oración al revés: \n" + textoAlReves;

   JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_btnValidarActionPerformed
    
   private int contarPalabras(String texto) {
        String[] palabras = texto.split("\\s+");
        return palabras.length;
    }
 
   private String reemplazarCaracteres(String texto) {
        texto = texto.replace('o', '$');
        texto = texto.replace('a', '@');
        return texto;
    }
   
   private String obtenerAlReves(String texto) {
        StringBuilder reverso = new StringBuilder(texto);
        return reverso.reverse().toString();
    }
    
    
    
     private void EspaciosCadena1(){
        int contador =0;
        String nombres = "juan maria pedro luis";
        for(int i = 0; i<nombres.length(); i++){
            if(nombres.charAt(i) ==' '){
                contador++;
            }
        }
        System.out.println("el numero de espacios en el texto: " +nombres+"\nson:"+contador);                                        
    }
    
     private void NumeroVocales(){
        int contA=0;
        int contE=0;
        int contI=0;
        int contO=0;
        int contU=0;
        
        String texto="el dia de ayer margarita julia y jorge salieron de excursion";
        for(int i=0; i<texto.length(); i++){
            if(texto.charAt(i) == 'a'){
                contA++;
            }else if(texto.charAt(i)== 'e'){
                contE++;
            }else if(texto.charAt(i)=='i'){
                contI++;
            }else if(texto.charAt(i)=='o'){
                contO++;
            }else if(texto.charAt(i)=='u'){
                contU++;
            }
        }
        System.out.println("Texto: "+texto+"\n Vocales A: "+contA+"\n Vocales E: "+contE+"\n Vocales I: "+contI+"\n Vocales O: "+contO+"\n Vocales U: "+contU);
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadenasClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadenasClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadenasClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadenasClase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadenasClase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
