/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author floow
 */
public class ComprobacionCadenas extends javax.swing.JFrame {

    /**
     * Creates new form ComprobacionCadenas
     */
    public ComprobacionCadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValidar = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValidarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtValidarMouseEntered(evt);
            }
        });
        txtValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidarActionPerformed(evt);
            }
        });
        txtValidar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValidarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValidarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValidarKeyTyped(evt);
            }
        });

        lblTitulo.setText("Validacion de cadenas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidarActionPerformed


    }//GEN-LAST:event_txtValidarActionPerformed

    private void txtValidarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidarKeyTyped

    }//GEN-LAST:event_txtValidarKeyTyped

    private void txtValidarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidarKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtValidarKeyPressed

    private void txtValidarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValidarKeyReleased

    }//GEN-LAST:event_txtValidarKeyReleased

    private void txtValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidarMouseClicked
        String validar = txtValidar.getText();
        this.comprobarEspacios(validar);
        this.separarCadenas(validar);

    }//GEN-LAST:event_txtValidarMouseClicked

    private void separarCadenas(String cadenas) {
        String[] subcadenas = cadenas.split(" ");
        String a;
        for (String x : subcadenas) {
            System.out.println(":" + x);
        }
        for (int i = 0; i <= subcadenas.length - 1; i++) {
            String name = "cadena" + i;
            String value = subcadenas[i];
            System.out.println(name+"="+value);
        }

    }

    private void comprobarEspacios(String validar) {
        int contador = 0;
        if (!validar.isEmpty()) {
            for (int i = 0; i <= validar.length() - 1; i++) {
                if (validar.charAt(i) == ' ') {
                    contador++;
                }
            }
            txtValidar.setText("El número de espacios en blanco en la cadena: " + validar + "son:" + contador);

        } else {
            txtValidar.setText("No se puede realizar la acción");
        }
    }

    private void txtValidarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidarMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_txtValidarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobacionCadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobacionCadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobacionCadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobacionCadenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobacionCadenas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtValidar;
    // End of variables declaration//GEN-END:variables
}
